# Generated by Django 2.1.3 on 2018-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmo_id', models.CharField(max_length=16)),
                ('station', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('radiation_time', models.FloatField()),
                ('avg_wind_speed', models.FloatField()),
                ('most_wind_direction', models.CharField(max_length=8)),
                ('max_wind_speed', models.FloatField()),
                ('wind_direction_at_max', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
